---
title: "HMM"
author: "Katharina Fijan"
date: "4/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE)
```


## Load Data & Packages
```{r}
library(tidyverse)
library(HMM)

data <- read.table('./data/TPP_proteasome_correlations.csv', sep=',', header = TRUE)
summary(data)
```

## Extract Data 
```{r}
complex1_df <- data %>% filter(bait == 'PSMA1', prey == 'PSMA2')
complex2_df <- data %>% filter(bait == 'PSMB2', prey == 'PSMC5') 
complex3_df <- data %>% filter(bait == 'PSMD13', prey == 'PSMG3') 
complex4_df <- data %>% filter(bait == 'PSMD7', prey == 'PSMD9') 
complex5_df <- data %>% filter(bait == 'PSMA5', prey == 'PSMD10') 

multi_obs <- paste(as.character(unlist(round(complex1_df$corr, 1))), as.character(unlist(round(complex2_df$corr, 1))), as.character(unlist(round(complex3_df$corr, 1))), as.character(unlist(round(complex4_df$corr, 1))), as.character(unlist(round(complex5_df$corr, 1))))



```


## Initialize HMM Model - Default Values
```{r}
#usage/defaults: initHMM(States, Symbols, startProbs=NULL, transProbs=NULL, emissionProbs=NULL)
states <- c("interaction", "no_interaction") #hidden states
symbols <- as.character(seq(from = -1.0, to = 1.0, by = 0.1)) #observed states - needs to be character dtype or error is thrown
pi <- NULL
T_ <- NULL
E_ <- NULL
hmm <- initHMM(states, symbols) #initialized model
print(hmm)
```


## Learn HMM - BaumWelch Algorithm
```{r}
#usage/defaults: baumWelch(hmm, observation, maxIterations=100, delta=1E-9, pseudoCount=0)

observed_data <- as.character(unlist(round(complex1_df$corr, 1))) #list of observed correlation values 
max_iterations <- 10000
delta=1E-9

learned_hmm <- baumWelch(hmm, observed_data, max_iterations, delta)
print(learned_hmm$hmm)
```


## Initialize HMM Model - Define Parameters
```{r}
#usage/defaults: initHMM(States, Symbols, startProbs=NULL, transProbs=NULL, emissionProbs=NULL)
states <- c("interaction", "no_interaction") #hidden states
symbols <- as.character(seq(from = 0.0, to = 1.0, by = 0.1)) #"correlation" values
pi <- c(0.5, 0.5)
T_ <- matrix(c(0.5, 0.5, 0.5, 0.5), nrow=2)
E_ <- learned_hmm$hmm$emissionProbs
hmm2<- initHMM(states, symbols, pi, T_, E_) #initialized model
print(hmm2)
```

## Learn HMM using Defined Params - BaumWelch Algorithm
```{r}
#usage/defaults: baumWelch(hmm, observation, maxIterations=100, delta=1E-9, pseudoCount=0)

observed_data <- as.character(unlist(abs(round(complex2_df$corr, 1)))) #list of observed correlation values 
max_iterations <- 10000
delta=1E-20

learned_hmm2 <- baumWelch(hmm2, observed_data)
print(learned_hmm2$hmm)
```

## Try aphid Package
```{r}
library(aphid)

#train(x, y, method = "Viterbi", seqweights = NULL, wfactor = 1, maxiter = 100, deltaLL = 1e-07,
 # logspace = "autodetect", quiet = FALSE, modelend = FALSE, pseudocounts = "Laplace", ...)

states <- c("begin", "interaction", "no_interaction")

### Define the transition probability matrix
T_ <- matrix(c(0, 0, 0, .5, .5, 0.75, 0.25, 0.25, 0.75), nrow = 3)
dimnames(T_) <- list(from = states, to = states) #names columns and rows for matrix

### Define the emission probability matrix
E_ <- matrix(c(rep(1/21, 21), rep(1/21, 21)), nrow = 2, byrow = TRUE)
dimnames(E_) <- list(states = states[-1], residues = symbols) #names columns and rows for matrix

#creates hmm structure
x2 <- structure(list(A = T_, E = E_), class = "HMM")

#plots image of HMM
plot.HMM(x2, main ="Starting HMM Model for Protein Interactions")


observed_data <- c(as.character(round(complex1_df$corr, 1)))
#dimnames(observed_data) <- list(states[1], states[1], states[1], states[0], states[0], states[1])

#trains hmm -- use 1 set of observations not multiple observations
hmm_aphid <- train(x2, observed_data, method="BaumWelch", maxiter=50, pseudocounts="Laplace")
hmm_aphid$A
hmm_aphid$E

```

## Playing around with aphid example data/code -- casino 
```{r}
data(casino) ##data used in examples

## the dishonest casino example from Durbin et al (1998)
states <- c("Begin", "Fair", "Loaded")
residues = paste(1:6)
A <- matrix(c(0, 0, 0, 0.99, 0.95, 0.1, 0.01, 0.05, 0.9), nrow = 3)
dimnames(A) <- list(from = states, to = states)
E <- matrix(c(rep(1/6, 6), rep(1/10, 5), 1/2), nrow = 2, byrow = TRUE)
dimnames(E) <- list(states = states[-1], residues = residues)
x <- structure(list(A = A, E = E), class = "HMM")
plot(x, main = "Dishonest casino hidden Markov model")

##deriveHMM 
derive  <- deriveHMM(list(casino))
derive$A
derive$E
```

```{r}
## Baum Welch training for standard HMMs:
  ## The dishonest casino example from Durbin et al (1998) chapter 3.2
states <- c("Begin", "Fair", "Loaded")
residues <- paste(1:6)
### Define the transition probability matrix
A <- matrix(c(0, 0, 0, 0.99, 0.95, 0.1, 0.01, 0.05, 0.9), nrow = 3)
dimnames(A) <- list(from = states, to = states)
### Define the emission probability matrix
E <- matrix(c(rep(1/6, 6), rep(1/10, 5), 1/2), nrow = 2, byrow = TRUE)
dimnames(E) <- list(states = states[-1], residues = residues)
### Build and plot the HMM object
x <- structure(list(A = A, E = E), class = "HMM")
op <- par(no.readonly = TRUE)
par(mfrow = c(2, 1))
plot(x, main = "Dishonest casino HMM before training")
data(casino)
x <- train(x, list(casino), method = "BaumWelch", deltaLL = 0.001)
plot(x, main = "Dishonest casino HMM after training")
par(op)
```

