---
title: "HMM"
author: "Katharina Fijan"
date: "4/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE)
```


## Load Data & Packages
```{r}
library(tidyverse)
library(aphid)

tpca_data <- read.table('~/Downloads/Proteasome_TPCA_Result.csv', sep=',', header =TRUE)
summary (tpca_data)

Exosome_TPCA_Distances <- read.csv("data/Exosome_TPCA_Result_pvalues.csv")
summary(Exosome_TPCA_Distances)

```

## Extract Data 
```{r}

# exo_pval_df <- Exosome_TPCA_Distances %>% filter(stage!= 'asynch')
# exo_pval_df <- exo_pval_df[order(exo_pval_df$bait, exo_pval_df$prey),]

exo_dist_df <- Exosome_TPCA_Distances %>% filter(stage!= 'asynch')
#sort df by cell cycle stage
exo_dist_df <- exo_dist_df[order(exo_dist_df$bait, exo_dist_df$prey),]

```

## learn HMM using aphid package
```{r}
### Set states
states <- c("begin", "interaction", "no_interaction")

### Define the transition probability matrix
T_ <- matrix(c(0, 0, 0, 0.5, 0.75, 0.75, 0.5, 0.25, 0.25), nrow = 3)
dimnames(T_) <- list(from = states, to = states) #names columns and rows for matrix

### Define the emission probability matrix
#Get the emission matrix for -1 to 1:
##Observations from -1 to 1
symbols = seq(from = -1.0, to = 1.0, by = 0.1)
##set an increasing probability from  0 to 1 spread out across the 20 observations
probs = seq(from = 0.0, to = 1.0, by = 0.05)
#Normalize so the rows will sum to 1 for each state
probs_increase_adjusted = probs * (1/sum(probs))
##get the reverse for the "no interaction" state
probs_decrease_adjusted = rev(probs_increase_adjusted)
##Set emission matrix
E_ <- matrix(c(probs_increase_adjusted, probs_decrease_adjusted), 2, byrow=TRUE)
#E_ <- matrix(c(rep(1/21, 21), rep(1/21, 21)), nrow = 2, byrow = TRUE)
dimnames(E_) <- list(states = states[-1], residues = symbols) #names columns and rows for matrix 

#creates hmm structure
x2 <- structure(list(A = T_, E = E_), class = "HMM")

#plots image of HMM
plot.HMM(x2, main ="Starting HMM Model for Protein Interactions")

observed_data <- c(as.character(round(psma1_df$corr, 1)))

#write function to loop through data and retrain model

#observed_data <- c(as.character(round(complex1_df$corr, 1)))
#dimnames(observed_data) <- list(states[1], states[1], states[1], states[0], states[0], states[1])

#trains hmm -- use 1 set of observations not multiple observations
hmm_aphid <- train(x2, observed_data, method="BaumWelch", maxiter=500, pseudocounts="Laplace")
hmm_aphid
hmm_aphid$A
hmm_aphid$E


plot.HMM(hmm_aphid, main="HMM Model After Training")
```

## Aphid & tpca Data
```{r}

states <- c("begin", "interaction", "no_interaction")

### Define the transition probability matrix
T_2 <- matrix(c(0, 0, 0, 0.5, 0.75, 0.75, 0.5, 0.25, 0.25), nrow = 3)
dimnames(T_2) <- list(from = states, to = states) #names columns and rows for matrix

### Define the emission probability matrix
symbols = seq(from = 0.0, to = 1.0, by = 0.1)
E_2 <- matrix(c(0, 1.0, 0.1, 0.9, 0.2, 0.8, 0.3, 0.7, 0.4, 0.6, 0.5, 0.5, 0.6, 0.4, 0.7, 0.3, 0.8, 0.2, 0.9, 0.1, 1.0, 0.0), nrow = 2) 
dimnames(E_2) <- list(states = states[2:3], residues = symbols) #names columns and rows for matrix 

#creates hmm structure
x_tpca <- structure(list(A = T_2, E = E_2), class = "HMM")

#plots image of HMM
#plot.HMM(x_tpca, main ="Starting HMM Model for Protein Interactions")

observed_data <- c(as.character(round(psma1_df_tpca$distance, 1)))
observed_df <- data.frame(actual = c(psma1_df_tpca$distance))
observed_df$binned <- ifelse(observed_df$actual > 1, '1.0', observed_df$actual) 

tpca1_train <- c(as.character(round(as.numeric(observed_df$binned, 1))))

#write function to loop through data and retrain model

#observed_data <- c(as.character(round(complex1_df$corr, 1)))
#dimnames(observed_data) <- list(states[1], states[1], states[1], states[0], states[0], states[1])

#trains hmm -- use 1 set of observations not multiple observations
hmm_aphid <- train(x_tpca, tpca1_train, method="BaumWelch", maxiter=500, pseudocounts="Laplace")
hmm_aphid
hmm_aphid$A
hmm_aphid$E

plot.HMM(hmm_aphid, main="HMM Model After Training")

hmm_tpcaE <- data.frame(t(hmm_aphid$E))

ggplot(data=hmm_tpcaE) + 
  geom_point(aes(x = seq(from = 0.0, to = 1.0, by = 0.1), y=interaction), fill='coral1',color='coral4') + 
  geom_line(aes(x = seq(from = 0.0, to = 1.0, by = 0.1), y=interaction), color='coral') +
  geom_point(aes(x = seq(from = 0.0, to = 1.0, by = 0.1), y=no_interaction), fill='cornflowerblue', color='darkslateblue') + 
  geom_line(aes(x = seq(from = 0.0, to = 1.0, by = 0.1), y=no_interaction), color='blue') +
  ggtitle("Learned Emissions Matrix") + 
  xlab("Correlation Values") +
  ylab("Probabilities") + 
  theme(legend.position="top") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

ggplot(data=data.frame(t(E_2))) + 
  geom_point(aes(x = seq(from = 0.0, to = 1.0, by = 0.1), y=interaction), fill='coral1',color='coral4') + 
  geom_line(aes(x = seq(from = 0.0, to = 1.0, by = 0.1), y=interaction), color='coral') +
  geom_point(aes(x = seq(from = 0.0, to = 1.0, by = 0.1), y=no_interaction), fill='cornflowerblue', color='darkslateblue') + 
  geom_line(aes(x = seq(from = 0.0, to = 1.0, by = 0.1), y=no_interaction), color='blue') +
  ggtitle("Initialized Emissions Matrix") + 
  xlab("Correlation Values") +
  ylab("Probabilities") + 
  theme(legend.position="top") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

```


### Try learning HMM using pvalues from exosome data -- distance data
```{r}
#train(x, y, method = "Viterbi", seqweights = NULL, wfactor = 1, maxiter = 100, deltaLL = 1e-07,
 # logspace = "autodetect", quiet = FALSE, modelend = FALSE, pseudocounts = "Laplace", ...)

states <- c("begin", "interaction", "no_interaction")

### Define the transition probability matrix
T_2 <- matrix(c(0, 0, 0, 0.5, 0.5, 0.5, 0.5,0.5, 0.5), nrow = 3)
dimnames(T_2) <- list(from = states, to = states) #names columns and rows for matrix

## emissions matrix

symbols = seq(from = 0.0, to = 1.0, by = 0.1)

E_2 <- matrix(c(0, 1.0, 0.1, 0.9, 0.2, 0.8, 0.3, 0.7, 0.4, 0.6, 0.5, 0.5, 0.6, 0.4, 0.7, 0.3, 0.8, 0.2, 0.9, 0.1, 1.0, 0.0), nrow = 2) 

dimnames(E_2) <- list(states = c(states[3], states[2]), residues = symbols) #names columns and rows for matrix 

#creates hmm structure
x_exo <- structure(list(A = T_2, E = E_2), class = "HMM")

#plots image of HMM
plot.HMM(x_exo, main ="Starting HMM Model for Protein Interactions")

#put data into correct format -- rounded to tenth's place and as character for package
observed_data <- c(as.character(round(exo_dist_df$distance, 1)))
observed_df <- data.frame(actual = c(exo_dist_df$distance))
observed_df$norm <- as.numeric(observed_df$actual)/as.numeric(max(observed_df$actual))

dist <- c(as.character(round(as.numeric(observed_df$norm, 1))))


#trains hmm 
hmm_aphid <- train(x_exo, dist, method="BaumWelch", logspace = FALSE, maxiter=500)
hmm_aphid
hmm_aphid$A
hmm_aphid$E

plot.HMM(hmm_aphid, main="HMM Model After Training")


hmm_distE <- data.frame(t(hmm_aphid$E))

#plot learned emissions matrix 
ggplot(data=hmm_distE) + 
  geom_point(aes(x = seq(from = 0.0, to = 1.0, by = 0.1), y=interaction), fill='coral1',color='coral4') + 
  geom_line(aes(x = seq(from = 0.0, to = 1.0, by = 0.1), y=interaction), color='coral') +
  geom_point(aes(x = seq(from = 0.0, to = 1.0, by = 0.1), y=no_interaction), fill='cornflowerblue', color='darkslateblue') +
  geom_line(aes(x = seq(from = 0.0, to = 1.0, by = 0.1), y=no_interaction), color='blue') +
  ggtitle("Learned Emissions Matrix") + 
  xlab("Correlation Values") +
  ylab("Probabilities") + 
  theme(legend.position="top") +
  theme_classic() +
  theme(plot.title = element_text(hjust = 0.5))

```

```{r}
#check histogram of data itself
hist(Exosome_TPCA_Distances$distance, xlab='Distance', main = "Distribution of Exosome Distances")

hist(Exosome_TPCA_Distances$pvalue)
```
